name: Reusable Backend CI

on:
  workflow_call:
    inputs:
      language:
        required: true
        type: string
      version:
        required: true
        type: string
      workdir:
        required: true
        type: string
      install_cmd:
        required: true
        type: string
      test_cmd:
        required: true
        type: string

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4

      - name: Setup Node.js
        if: ${{ inputs.language == 'node' }}
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: ${{ inputs.version }}
          cache: npm

      - name: Setup Python
        if: ${{ inputs.language == 'python' }}
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version: ${{ inputs.version }}

      - name: Setup Java
        if: ${{ inputs.language == 'java' }}
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4
        with:
          distribution: temurin
          java-version: ${{ inputs.version }}

      - name: Install
        working-directory: ${{ inputs.workdir }}
        run: ${{ inputs.install_cmd }}
        env:
          CI: true

      - name: Test
        working-directory: ${{ inputs.workdir }}
        run: ${{ inputs.test_cmd }}
        env:
          CI: true

