name: Reusable Frontend CI

on:
  workflow_call:
    inputs:
      workdir:
        required: true
        type: string
      pkg_manager:
        required: false
        type: string
        default: pnpm
      install_cmd:
        required: false
        type: string
        default: pnpm i --frozen-lockfile
      test_cmd:
        required: false
        type: string
        default: pnpm test -- --ci
      node_version:
        required: false
        type: string
        default: '20'

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: ${{ inputs.node_version }}
          cache: ${{ inputs.pkg_manager }}
          cache-dependency-path: ${{ inputs.workdir }}/**/*lock*.{json,yaml}
      - name: Install
        working-directory: ${{ inputs.workdir }}
        run: ${{ inputs.install_cmd }}
        env:
          CI: true
      - name: Test
        working-directory: ${{ inputs.workdir }}
        run: ${{ inputs.test_cmd }}
        env:
          CI: true

